In [1]:
import pandas as pd
from scipy import stats

In [2]:
from IPython.display import display

In [3]:
# Output markdown to cells
from IPython.display import Markdown

In [4]:
# Function for description of dataframes
def resumetable(df):
    print(f"Dataset Shape: {df.shape}")
    summary = pd.DataFrame(df.dtypes,columns=['dtypes'])
    summary = summary.reset_index()
    summary['Name'] = summary['index']
    summary = summary[['Name','dtypes']]
    summary['Missing'] = df.isnull().sum().values    
    summary['Uniques'] = df.nunique().values
    summary['First Value'] = df.loc[0].values
    summary['Second Value'] = df.loc[1].values
    summary['Third Value'] = df.loc[2].values

    for name in summary['Name'].value_counts().index:
        summary.loc[summary['Name'] == name, 'Entropy'] = round(stats.entropy(df[name].value_counts(normalize=True), base=2),2) 

    return summary

---
## Consumer household data

In [5]:
# Read the customer household data from their API
url_path = 'https://data.gov.au/dataset/4e21dea3-9b87-4610-94c7-15a8a77907ef/resource/0404c872-8a83-40e6-9c04-88dfec125aee/download/sgsc-ct_customer-household-data-revised.csv'
household_df = pd.read_csv(url_path)

In [6]:
# Trim leading and trailing whitespaces in column names
household_df.columns = household_df.columns.str.strip()

----
### Column description table

In [7]:
resumetable(household_df)

Dataset Shape: (78720, 46)

,Name,dtypes,Missing,Uniques,First Value,Second Value,Third Value,Entropy
0,CUSTOMER_KEY,int64,0,78720,8459115,10015988,8922450,16.26
1,TRIAL_CUSTOMER_TYPE,object,0,3,Retail,Retail,Retail,0.64
2,CONTROL_GROUP_FLAG,object,0,2,N,N,N,0.18
3,TARIFF_PRODUCT_CD,object,68881,6,NaN,NaN,NaN,1.95
4,FEEDBACK_TECH1_PRODUCT_CD,object,68954,4,NaN,NaN,NaN,1.81
5,FEEDBACK_TECH2_PRODUCT_CD,object,77968,3,NaN,NaN,NaN,1.18
6,LIFESTYLE_AUDIT_PRODUCT_CD,object,78537,1,NaN,NaN,NaN,0.00
7,INFERRED_CELL,int64,0,103,14,60,28,5.23
8,VERIFIED_CELL,float64,74646,93,NaN,NaN,NaN,5.47
9,SERVICE_TYPE,object,0,1,Domestic,Domestic,Domestic,0.00
10,GENERAL_SUPPLY_CNT,int64,0,5,1,1,1,0.14
11,CONTROLLED_LOAD_CNT,int64,0,4,0,0,0,0.39
12,NET_SOLAR_CNT,int64,0,3,0,0,0,0.04
13,GROSS_SOLAR_CNT,int64,0,3,0,0,0,0.03
14,OTHER_LOAD_CNT,int64,0,6,0,0,0,0.02
15,SERVICE_LOC_STATUS_NAME,object,0,8,Not a Customer,Not a Customer,Not a Customer,0.92
16,ASSRTD_CLIMATE_ZONE_CD,int64,0,2,5,5,5,0.52
17,ASSRTD_CLIMATE_ZONE_DESC,object,0,2,Warm temperate,Warm temperate,Warm temperate,0.52
18,ASSRTD_DWELLING_TYPE_CD,object,0,2,NotUnit,NotUnit,NotUnit,0.72
19,ASSRTD_GAS_USAGE_GROUP_CD,object,0,3,MED,LOW,HI,1.26
20,ASSRTD_ELECTRICITY_USE_GRP_CD,object,0,3,LOW,MED,LOW,1.46
21,DWELLING_TYPE_CD,object,74652,3,NaN,NaN,NaN,0.85
22,DRYER_USAGE_CD,object,66171,4,NaN,NaN,NaN,1.71
23,REDUCING_CONSUMPTION_CD,object,66171,4,NaN,NaN,NaN,1.54
24,AIRCON_TYPE_CD,object,70653,3,NaN,NaN,NaN,1.12
25,NUM_REFRIGERATORS,float64,66170,10,NaN,NaN,NaN,1.37
26,NUM_ROOMS_HEATED,float64,66170,14,NaN,NaN,NaN,1.24
27,HAS_GENERATION,object,0,2,N,N,N,0.05
28,HAS_INTERNET_ACCESS,object,60349,2,NaN,NaN,NaN,0.59
29,HAS_GAS,object,68839,2,NaN,NaN,NaN,0.71
30,HAS_GAS_HEATING,object,68839,2,NaN,NaN,NaN,0.89
31,HAS_GAS_HOT_WATER,object,68839,2,NaN,NaN,NaN,0.84
32,HAS_GAS_COOKING,object,68839,2,NaN,NaN,NaN,0.79
33,HAS_POOLPUMP,object,60349,2,NaN,NaN,NaN,0.99
34,HAS_AIRCON,object,60349,2,NaN,NaN,NaN,0.80
35,HAS_GAS_OTHER_APPLIANCE,object,68839,2,NaN,NaN,NaN,0.97
36,IS_HOME_DURING_DAYTIME,object,60349,2,NaN,NaN,NaN,0.91
37,HAS_AGREED_TO_SMS,object,60349,2,NaN,NaN,NaN,0.51
38,SMART_METER_INSTALLATION_DATE,object,64949,409,NaN,NaN,NaN,8.06
39,LIFESTYLE_AUDIT_PERFORMED_DATE,float64,78720,0,NaN,NaN,NaN,0.00
40,PROVISIONING_COMPLETE_DATE,object,71571,236,NaN,NaN,NaN,6.90
41,OFFER_WITHDRAWN_DATE,object,76283,52,NaN,NaN,NaN,5.01
42,ACCEPTANCE_WITHDRAWN_DATE,object,76050,184,NaN,NaN,NaN,7.22
43,OPERATION_START_DATE,object,71571,236,NaN,NaN,NaN,6.90
44,OPERATION_FINISH_DATE,object,71571,274,NaN,NaN,NaN,2.12
45,AGREEMENT_EXIT_REASON,object,71571,7,NaN,NaN,NaN,1.70

|           Column            |                Description             |Reliability model| Future model  | 
|-----------------------------|----------------------------------------|:---------------:|:-------------:|
CUSTOMER_KEY                  |            Unique customer ID          |        Y        |               |
TRIAL_CUSTOMER_TYPE           |Consumer type (network, retail, control)|        Y        |               |
CONTROL_GROUP_FLAG            |Customer part (or not) of control group |   N (redudant)  |               |
TARIFF_PRODUCT_CD             |       Type of tariff product           |        Y        |               |
GENERAL_SUPPLY_CNT            |     Number of general supply meters    |      Maybe?     |               |
CONTROLLED_LOAD_CNT           |        Number of controlled loads      |      Maybe?     |               |
NET_SOLAR_CNT                 |  Number of net solar generation meters |        N        |               |
GROSS_SOLAR_CNT               |Number of gross solar generation meters |        N        |               |
OTHER_LOAD_CNT                |          Number of other meters        |        N        |               |
SERVICE_LOC_STATUS_NAME       |If stayed on the trial for the duration |        N        |               |
ASSRTD_CLIMATE_ZONE_DESC      |     Details of assumed climate zone    |      Maybe?     |               |
ASSRTD_DWELLING_TYPE_CD       |          Assumed Dwelling Type         |        Y        |               |
ASSRTD_GAS_USAGE_GROUP_CD     |         Assumed Gas Usage Amount       |        Y        |               |
ASSRTD_ELECTRICITY_USE_GRP_CD |    Assumed Electricity Usage Amount    |        Y        |               |
DWELLING_TYPE_CD              |          Stated Dwelling Type          |        Y        |               |
DRYER_USAGE_CD                |       Clothes Dryer Usage level        |        Y        |               |
REDUCING_CONSUMPTION_CD       | Stated effort level for power reduction|        Y        |               | 
AIRCON_TYPE_CD                |     Airconditioner Installation Type   |        Y        |               |
NUM_REFRIGERATORS             |         Number of refrigerators        |        Y        |               |
NUM_ROOMS_HEATED              |          Number of rooms heated        |        Y        |               |
HAS_GENERATION                |      Has a way of power generation     |        Y        |               |
HAS_INTERNET_ACCESS           |      Has internet access               |        N        |               |
HAS_GAS                       |                 Has gas                |        Y        |               |
HAS_GAS_HEATING               |           Uses gas for heating         |        Y        |               |
HAS_GAS_HOT_WATER             |          Uses gas for hot water        |        Y        |               |
HAS_GAS_COOKING               |        Uses gas for cooking oven       |        Y        |               |
HAS_POOLPUMP                  |           Has a pump for a pool        |        Y        |               |
HAS_AIRCON                    |          Has airconditiong system      |        Y        |               |
HAS_GAS_OTHER_APPLIANCE       |      Has other gas-using appliances    |      Maybe?     |               |
IS_HOME_DURING_DAYTIME        |Is home someone on weekdays (stnd-hours)|        Y        |               |
HAS_AGREED_TO_SMS             |      Agreed to be contacted via SMS    |        N        |               |
SMART_METER_INSTALLATION_DATE |      Smart meter intallation date      |        N        |               |
PROVISIONING_COMPLETE_DATE    |Datetime when product offers to customer was provisioned or deprovisioned| N| |
OFFER_WITHDRAWN_DATE          |       Network Offer Withdrawn Date     |        N        |               |
ACCEPTANCE_WITHDRAWN_DATE     |        Acceptance Withdrawal Date      |        N        |               |
OPERATION_START_DATE          |Customer tariff product trial period begins|     N        |               |
OPERATION_FINISH_DATE         |Customer tariff product trial period ends|       N        |               |
AGREEMENT_EXIT_REASON         |           Customer exit reason         |        N        |               |

#### Products offered

There are two trials completed as part of the Smart Grid, Smart City Customer Applications Program:

* **Network trials**. These trials tested feedback technologies, financial incentives (rebates) and a lifestyle audit.
* **Retail trials**. This trials included alternative electricity tariffs either as standalone products or bundled with feedback technologies

The products offered during the trial can be classified in the following categories:
1. Feedback technologies
2. Peak event products
3. Combinations of the above

The products offered are the following:

| Product ID     | Marketing name                                    | Pricing/Incentive      | Technology*                                   |   |
|----------------|---------------------------------------------------|------------------------|-----------------------------------------------|---|
| **Network** |                                                   |                        |                                               |   |
| N1             | SGSC Home Energy Online                           | -                      | Online portal                                 |   |
| N2             | SGSC Home Energy Monitor                          | -                      | Home energy monitor                           |   |
| N3             | SGSC Assessment                                    | Home Energy Assessment | -                                             | - |
| N4             | SGSC Home Energy Rebate                           | Dynamic peak rebate    | -                                             |   |
| N5             | SGSC Home Energy Network + Home Energy Online     | -                      | Home area network (smart plugs) Online portal |   |
| N6             | SGSC Home Energy Rebate + Home Energy Monitor     | Dynamic peak rebate    | Home energy monitor                           |   |
| N7             | SGSC Home Energy Online + Home Energy Monitor     | -                      | Online portal Home energy monitor             |   |
| N8             | SGSC Home Energy Air                              |                        |                                               |   |
| N9             | RedFlow Storage System                             |                        |                                               |   |
| N10            | Bluegen Gas Fuel Cell                             |                        |                                               |   |
| **Retail**  |                                                   |                        |                                               |   |
| R1             | BudgetSmart                                       | Top up reward plan     | -                                             |   |
| R2             | BudgetSmart with PowerSmart Monitor               | Top up reward plan     | Home energy monitor                           |   |
| R3             | BudgetSmart with PowerSmart Online                | Top up reward plan     | Online portal                                 |   |
| R4             | BudgetSmart with PowerSmart Online & Home Control | Top up reward plan     | Online portal Home area network (smart plugs) |   |
| R5             | Flowsmart with Powersmart Online                  |          Direct Control A/C              |     Online portal                                          |   |
| R6             | PriceSmart                                        | Dynamic peak pricing   | -                                             |   |
| R7             | PriceSmart with PowerSmart Monitor                | Dynamic peak pricing   | Home energy monitor                           |   |
| R8             | PriceSmart with PowerSmart Online                 | Dynamic peak pricing   | Online portal                                 |   |
| R9             | PriceSmart with PowerSmart Online & Home Control  | Dynamic peak pricing   | Online portal Home area network (smart plugs) |   |
| R10            | SeasonSmart                                       | Seasonal time-of-use   | -                                             |   |
| R11            | SeasonSmart with PowerSmart Monitor               | Seasonal time-of-use   | Home energy monitor                           |   |
| R12            | SeasonSmart with PowerSmart Online                | Seasonal time-of-use   | Online portal                                 |   |

First we **drop** the columns in which we are **not** interested. 

In this analysis we are only interested only in the *tariff* products. So we drop the following columns:

* `FEEDBACK_TECH1_PRODUCT_CD` : primary feedback technology product
* `FEEDBACK_TECH2_PRODUCT_CD` : secondary feedback technology product
* `LIFESTYLE_AUDIT_PRODUCT_CD` : lifestyle audit product

There are also *redudant* columns that we need to drop:
* `INFERRED_CELL`: Internal Project Reference 
* `VERIFIED_CELL`: Internal Project Reference
* `SERVICE_TYPE` : All customers here are domestic. Redudant.
* `ASSRTD_CLIMATE_ZONE_CD` : Redudant, keep only the description column.

We are also not interested in the *date-related* columns. So we drop the following: 
* `LIFESTYLE_AUDIT_PERFORMED_DATE` : Not interested in audit products.
* `SMART_METER_INSTALLATION_DATE`
* `LIFESTYLE_AUDIT_PERFORMED_DATE`
* `PROVISIONING_COMPLETE_DATE`
* `OFFER_WITHDRAWN_DATE`
* `ACCEPTANCE_WITHDRAWN_DATE`
* `OPERATION_START_DATE`
* `OPERATION_FINISH_DATE`

Also the following columns are not informative for response, so they will not be included in the analysis:
* `HAS_AGREED_TO_SMS`
* `AGREEMENT_EXIT_REASON`

In [8]:
# Drop non-related tariff cols
tariff_col_list = ['FEEDBACK_TECH1_PRODUCT_CD', 'FEEDBACK_TECH2_PRODUCT_CD', 'LIFESTYLE_AUDIT_PRODUCT_CD']

# Drop redudant cols
redud_col_list = ['INFERRED_CELL', 'VERIFIED_CELL', 'SERVICE_TYPE', 'ASSRTD_CLIMATE_ZONE_CD']

# Columns with dates
date_col_mask = household_df.columns.str.contains('DATE')
date_col_list = list(household_df.columns[date_col_mask].values)

# Non-informative columns
non_info_col_list = ['HAS_AGREED_TO_SMS', 'AGREEMENT_EXIT_REASON']

drop_col_list = tariff_col_list + redud_col_list + date_col_list + non_info_col_list

household_df.drop(drop_col_list, axis='columns', inplace=True)

----

#### Control group

In [9]:
# Get the unique flags
household_df.CONTROL_GROUP_FLAG.unique()

array(['N', 'Y'], dtype=object)

In [10]:
control_group_prop = (household_df.CONTROL_GROUP_FLAG == 'Y').sum()/household_df.shape[0]
display(Markdown("It seems that the **{}%** of the consumers is part of the control group.".format(round(control_group_prop*100,3))))

It seems that the **2.659%** of the consumers is part of the control group.

#### Tariff products
The tariff products offered during the trials were:
* `Peak Rebate` (dynamic peak incentive payments)
* `PriceSmart` (dynamic peak pricing)
* `SeasonSmart` (seasonal ToU pricing)
* `BudgetSmart` (top up reward plan)

The `Peak Rebate`, `BudgetSmart` are **incentive-based** DR products ??, whereas `PriceSmart`, `SeasonSmart` are **price-based** ones.

The **tariff products** found in the data are:

In [11]:
tariff_prods = household_df.TARIFF_PRODUCT_CD.unique()

display(Markdown(''.join(['- {}\n'.format(prod) for prod in tariff_prods])))

- nan
- NETDPRPPE
- EA-DPP
- EA-TOPUP
- EA-STOU
- EA-ILAC
- NETAIR

The `NET` prefix stands for products provided by the *distribution network*, `EA` prefix stands for products provided by retailers.

The mapping to the tariff products mentioned above is:
* `NETDPRPPE` --> Peak Rebate 
* `EA-DPP`    --> PriceSmart (*Dynamic Peak Pricing*)
* `EA-TOPUP`  --> BudgetSmart (*Top-Up reward plan*) --> Prepayment plan with rewards, like [this one](https://powerni.co.uk/help-support/keypad/keypad-reward/)
* `EA-STOU`   --> SeasonSmart (*Seasonal ToU*)
* `EA-ILAC`   --> Interruptible A/C control (*Direct control*)
* `NETAIR`    --> SGSC Home Energy Air (*only 3 customers...*)

The number of customers per tariff product is given by the following table:

In [12]:
no_customers_prod_df = household_df.groupby('TARIFF_PRODUCT_CD').count()
pd.DataFrame(no_customers_prod_df.CUSTOMER_KEY)

                   CUSTOMER_KEY
TARIFF_PRODUCT_CD
EA-DPP                     3771
EA-ILAC                     112
EA-STOU                    1612
EA-TOPUP                   2995
NETAIR                        3
NETDPRPPE                  1346

In [13]:
non_tariff_prop = household_df.TARIFF_PRODUCT_CD.isnull().sum()/household_df.shape[0]
display(Markdown("It seems that the **{}%** of the consumers doesn't have a tariff product.".format(round(non_tariff_prop*100,3))))

It seems that the **87.501%** of the consumers doesn't have a tariff product.

#### Data subset of interest

So in our case we are interested only in the customers that belong to the following products:
* NETDPRPPE 
* EA-DPP 
* EA-TOPUP
* EA-STOU
* EA-ILAC

The dataset of interest is:

In [14]:
# Get the subset of data interesting only for our analysis
household_tariff_mask = (household_df.TARIFF_PRODUCT_CD.notna()) & (household_df.TARIFF_PRODUCT_CD != 'NETAIR')
household_tariff_df = household_df[household_tariff_mask]

household_tariff_df

,CUSTOMER_KEY,TRIAL_CUSTOMER_TYPE,CONTROL_GROUP_FLAG,TARIFF_PRODUCT_CD,GENERAL_SUPPLY_CNT,CONTROLLED_LOAD_CNT,NET_SOLAR_CNT,GROSS_SOLAR_CNT,OTHER_LOAD_CNT,SERVICE_LOC_STATUS_NAME,...,HAS_GENERATION,HAS_INTERNET_ACCESS,HAS_GAS,HAS_GAS_HEATING,HAS_GAS_HOT_WATER,HAS_GAS_COOKING,HAS_POOLPUMP,HAS_AIRCON,HAS_GAS_OTHER_APPLIANCE,IS_HOME_DURING_DAYTIME
4,8922472,Network,N,NETDPRPPE,1,0,0,0,0,Trial Closed,...,N,Y,Y,N,Y,Y,N,Y,N,N
13,9898684,Retail,N,EA-DPP,1,0,0,0,0,Moved Out,...,N,Y,NaN,NaN,NaN,NaN,N,Y,NaN,Y
15,9898698,Retail,N,EA-TOPUP,1,0,0,0,0,SGSC Declined,...,N,Y,NaN,NaN,NaN,NaN,N,N,NaN,N
17,9898702,Retail,N,EA-TOPUP,2,1,0,0,0,Trial Closed,...,N,Y,NaN,NaN,NaN,NaN,N,N,NaN,Y
19,8602358,Retail,N,EA-STOU,1,0,0,0,0,Customer Withdrew,...,N,Y,NaN,NaN,NaN,NaN,N,Y,NaN,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78692,8940870,Retail,N,EA-STOU,1,0,0,0,0,Customer Withdrew,...,N,Y,NaN,NaN,NaN,NaN,Y,Y,NaN,N
78697,9825248,Retail,N,EA-DPP,1,0,0,0,0,Customer Withdrew,...,N,Y,NaN,NaN,NaN,NaN,N,N,NaN,Y
78712,8963598,Retail,N,EA-DPP,1,0,0,0,0,Customer Withdrew,...,N,Y,NaN,NaN,NaN,NaN,N,Y,NaN,Y
78713,8629743,Network,N,NETDPRPPE,1,1,0,0,0,Trial Closed,...,N,Y,N,N,N,N,N,Y,N,N
78714,10898651,Retail,N,EA-DPP,1,0,0,0,0,SGSC Declined,...,N,Y,NaN,NaN,NaN,NaN,N,Y,NaN,Y

For the analysis of how households have responded to peak events we only include the ones which particiapted in the **Dynamic Peak Rebate** (`NETDPRPPE`) scheme.

In [15]:
household_DPR_df = household_df[household_df.TARIFF_PRODUCT_CD == 'NETDPRPPE']
household_DPR_df

,CUSTOMER_KEY,TRIAL_CUSTOMER_TYPE,CONTROL_GROUP_FLAG,TARIFF_PRODUCT_CD,GENERAL_SUPPLY_CNT,CONTROLLED_LOAD_CNT,NET_SOLAR_CNT,GROSS_SOLAR_CNT,OTHER_LOAD_CNT,SERVICE_LOC_STATUS_NAME,...,HAS_GENERATION,HAS_INTERNET_ACCESS,HAS_GAS,HAS_GAS_HEATING,HAS_GAS_HOT_WATER,HAS_GAS_COOKING,HAS_POOLPUMP,HAS_AIRCON,HAS_GAS_OTHER_APPLIANCE,IS_HOME_DURING_DAYTIME
4,8922472,Network,N,NETDPRPPE,1,0,0,0,0,Trial Closed,...,N,Y,Y,N,Y,Y,N,Y,N,N
71,8921900,Network,N,NETDPRPPE,1,0,0,0,0,Trial Closed,...,N,Y,Y,N,Y,Y,N,N,N,N
74,8921908,Network,N,NETDPRPPE,1,0,0,0,0,Trial Closed,...,N,Y,N,N,N,N,N,N,N,N
78,8921922,Network,N,NETDPRPPE,1,0,0,0,0,Trial Closed,...,N,Y,Y,N,Y,Y,N,Y,Y,N
93,11176151,Network,N,NETDPRPPE,1,0,0,0,0,Trial Closed,...,N,Y,Y,N,N,Y,N,Y,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78454,9083434,Network,N,NETDPRPPE,1,0,0,0,0,Trial Closed,...,N,Y,Y,Y,Y,N,Y,Y,N,N
78654,10640425,Network,N,NETDPRPPE,1,0,0,0,0,Trial Closed,...,N,Y,Y,Y,Y,Y,N,Y,N,N
78656,10640431,Network,N,NETDPRPPE,1,1,0,0,0,Trial Closed,...,N,Y,Y,N,N,Y,N,N,N,N
78685,10662613,Network,N,NETDPRPPE,1,0,0,0,0,Trial Closed,...,N,Y,Y,Y,N,Y,Y,N,N,N
78713,8629743,Network,N,NETDPRPPE,1,1,0,0,0,Trial Closed,...,N,Y,N,N,N,N,N,Y,N,N

#### Missing values
There are different ways to handle missing data. The naive and simpler way is to discarf the cases where there are incomplete data. There is a potential bias due to missing data, which depends on the mechanism causing the data to be missing. If the missing data are MCAR the `complete case analysis` will have a reduced statistical power due to the reduced sample size, but the observed data will not be biased. When missing data are not MCAR, the complete case analysis estimate of the intervention effect might be biased, i.e., there will often be a risk of overestimation of benefit and underestimation of harm.

In the presence of *Missing At Random (MAR)*, methods such as `multiple imputation` or `full information direct maximum likelihood` may lead to unbiased results. But it is the not always the case that this assumption can be made.

For more info see [here](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-017-0442-1).

In [16]:
# Percentage of missing values per household feature
missing_proportion = household_DPR_df.isna().sum()/household_DPR_df.shape[0]
missing_proportion

CUSTOMER_KEY                     0.000000
TRIAL_CUSTOMER_TYPE              0.000000
CONTROL_GROUP_FLAG               0.000000
TARIFF_PRODUCT_CD                0.000000
GENERAL_SUPPLY_CNT               0.000000
CONTROLLED_LOAD_CNT              0.000000
NET_SOLAR_CNT                    0.000000
GROSS_SOLAR_CNT                  0.000000
OTHER_LOAD_CNT                   0.000000
SERVICE_LOC_STATUS_NAME          0.000000
ASSRTD_CLIMATE_ZONE_DESC         0.000000
ASSRTD_DWELLING_TYPE_CD          0.000000
ASSRTD_GAS_USAGE_GROUP_CD        0.000000
ASSRTD_ELECTRICITY_USE_GRP_CD    0.000000
DWELLING_TYPE_CD                 0.000743
DRYER_USAGE_CD                   0.000743
REDUCING_CONSUMPTION_CD          0.000743
AIRCON_TYPE_CD                   0.341753
NUM_REFRIGERATORS                0.000743
NUM_ROOMS_HEATED                 0.000743
HAS_GENERATION                   0.000000
HAS_INTERNET_ACCESS              0.000000
HAS_GAS                          0.000000
HAS_GAS_HEATING                  0.000000
HAS_GAS_HOT_WATER                0.000000
HAS_GAS_COOKING                  0.000000
HAS_POOLPUMP                     0.000000
HAS_AIRCON                       0.000000
HAS_GAS_OTHER_APPLIANCE          0.000000
IS_HOME_DURING_DAYTIME           0.000000
dtype: float64

In [17]:
high_missing_cols = missing_proportion[missing_proportion > 0.1].index.values
no_missing_entries = household_DPR_df[high_missing_cols].isna().sum()
display(Markdown("The features with a high percentage of missing data ($>10\%$) are `{}` with a total number of **{}** missing entries.".format(high_missing_cols, int(no_missing_entries))))

The features with a high percentage of missing data ($>10\%$) are `['AIRCON_TYPE_CD']` with a total number of **460** missing entries.

This could be because not everyone has an AC system, so we check if this missing values are because of that.

In [18]:
# Number of missing AC type entries when they don't have AC.
household_DPR_df[household_DPR_df.HAS_AIRCON == 'N']['AIRCON_TYPE_CD'].shape

(459,)

Therefore all the missing values except one are because of this. Because of the really low percentages of missing values in the other features ($<0.1%$) we can safely use *complete case analysis*.

In [19]:
# Write it a csv file for the next steps of the analysis
household_DPR_df.to_csv('data/household_DPR_df.csv', index=False)